### ISSUE TITLE
Can't compile with go-ipfs because of hardcoded gx imports

### ISSUE THREAD

**Issue by AminArria** [decentraland/content-service#30]
We can't compile using Go 1.11 modules, it gives the following error: 
```
build github.com/decentraland/content-service: cannot find module for path gx/ipfs/QmPJUtEJsm5YLUWhF6imvyCH8KZXRJa9Wup7FDMwTy5Ufz/backoff
```

https://github.com/ipfs/go-ipfs/pull/5435

https://github.com/ipfs/go-ipfs/issues/4831

https://github.com/ipfs/gx-workspace/issues/20

https://github.com/ipfs/go-ipfs/issues/5054
